### PR TITLE
[WIP] Contact Page

### PR DESCRIPTION
**Pull request by jcollins1119**
Created a "Contact Us" tab on the main COS page.  The page contains text box inputs for contact information, checkbox inputs for how the user is interested in using OSF, a text input for other information, and a send button input.  I edited the _base.mako file to include a link in the header to the contact page, but doing so caused the header to move into the wrong place, so additional reformatting of the navigation bar in the header would be required before implementation. The page currently has no back-end implementation, so pressing send doesn't do anything except reset the form.  I've included a screenshot of what the page looks like.

[WIP]

contact

### CODE REVIEW

**Comment by mattspitzer** [comment]
The Salesforce embed code











<META HTTP-EQUIV="Content-type" CONTENT="text/html; charset=UTF-8">







<form action="https://www.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8" method="POST">
<input type=hidden name="oid" value="00Dj0000001p7Or">
<input type=hidden name="retURL" value="https://osf.io/">






<label for="first_name">First Name</label><input  id="first_name" maxlength="40" name="first_name" size="20" type="text" /><br>
<label for="last_name">Last Name</label><input  id="last_name" maxlength="80" name="last_name" size="20" type="text" /><br>
<label for="email">Email</label><input  id="email" maxlength="80" name="email" size="20" type="text" /><br>
<label for="company">Company</label><input  id="company" maxlength="40" name="company" size="20" type="text" /><br>
<label for="title">Title</label><input  id="title" maxlength="40" name="title" size="20" type="text" /><br>
<label for="description">Description</label><textarea name="description"></textarea><br>
Interest:<select  id="00Nj000000B5oFV" multiple="multiple" name="00Nj000000B5oFV" title="Interest"><option value="OSF4I">OSF4I</option>
<option value="Stats Consulting or Workshop">Stats Consulting or Workshop</option>
<option value="TOP Guidelines">TOP Guidelines</option>
<option value="OSF">OSF</option>
<option value="Preregistration Challenge">Preregistration Challenge</option>
<option value="Development Projects">Development Projects</option>
<option value="OSF for Meetings">OSF for Meetings</option>
<option value="Funding COS">Funding COS</option>
<option value="Other">Other</option>
</select><br>
<label for="lead_source">Lead Source</label><select  id="lead_source" name="lead_source"><option value="">--None--</option><option value="Prereg Challenege">Prereg Challenege</option>
<option value="Advertisement">Advertisement</option>
<option value="Employee Referral">Employee Referral</option>
<option value="External Referral">External Referral</option>
<option value="Partner">Partner</option>
<option value="Public Relations">Public Relations</option>
<option value="Seminar - Internal">Seminar - Internal</option>
<option value="Seminar - Partner">Seminar - Partner</option>
<option value="Trade Show">Trade Show</option>
<option value="Web">Web</option>
<option value="Word of mouth">Word of mouth</option>
<option value="Other">Other</option>
</select><br>
<input type="submit" name="submit">
</form>

**Comment by mattspitzer** [comment]
@saradbowman can this be added to upcoming prioritization? Happy to discuss further if needed.

**Comment by saradbowman** [comment]
@mattspitzer we can get this in queue along with the other cos.io change for prereg. Is there a spec for this work or is this PR all the info we have?

**Comment by mattspitzer** [comment]
I thought there was another github issue but can't find it. Otherwise there is the original JIRA card I submitted to ErinM: https://openscience.atlassian.net/browse/NCP-564

Let me know what else you would need

**Comment by erinspace** [comment]
Added in #719!

**Pull request closed without merging**
