### PR TITLE
[WIP] Update sponsors page - closes #271

### LINKED ISSUE #271: Add sponsors and sponsor information
Rackspace - Monthly credit for cloud services, http://www.rackspace.com/

rackspace logo_no 1 mgd_no tag_color-2

Spanning -Non-profit discount on "Backup For Google Apps", http://spanning.com/

We meed more information under Ready Force and Zipfian.

 @AndrewSallans can add more details on those.

### PR DESCRIPTION
**Pull request by erinspace**
Not quite ready yet, but has most of the proposed fixes from #271

### CODE REVIEW

**Comment by lyndsysimon** [comment]
@erinspace - thoughts on this? Do we need to resolve the conflicts and merge this in, or should we close it?

**Comment by GaryKriebel** [comment]
Looks like the sponsors still need updating.

**Comment by lyndsysimon** [comment]
I spoke briefly with Erin, and it looks like this change will need approval from the Community team before deployment.

I'll change the title to indicate that it isn't ready to be merged.

**Comment by AndrewSallans** [comment]
I can review the changes next week and then we should be able to merge.
Could somebody help me remember to review it?

**Comment by lbanner** [comment]
:+1: - Yes.

**Comment by lbanner** [comment]
@AndrewSallans ... reminder, as requested: Changes reviewed by you yet? Thanks.

**Pull request merged**
