### PR TITLE
Add New staff pictures, interns, resolves merge conflicts from #367

### PR DESCRIPTION
**Pull request by erinspace**
resolves conflicts from @jlcohoon's PR - https://github.com/CenterForOpenScience/centerforopenscience.org/pull/367

### CODE REVIEW

**Comment by GaryKriebel** [comment]
Who resets the server so that the merged changes appear?

**Comment by erinspace** [comment]
@lyndsysimon is on it, should be done soon

**Comment by lbanner** [comment]
Good.

On Thu, May 28, 2015 at 1:55 PM, Erin Braswell notifications@github.com
wrote:

> @lyndsysimon https://github.com/lyndsysimon is on it, should be done
> soon
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CenterForOpenScience/centerforopenscience.org/pull/369#issuecomment-106528517
> .

## 

Larry Banner
Technical Project Manager
Center for Open Science http://centerforopenscience.org/
210 Ridge McIntire Road, Suite 500
Charlottesville, VA 22903-5803
804.432.9522

---

## "We are such little men when the stars come out" - Hermann Hagedorn, 1882

**Comment by erinspace** [comment]
@GaryKriebel @lbanner updated now! Thanks @lyndsysimon!

**Comment by lbanner** [comment]
Appreciate it.

**Pull request merged**
