### PR TITLE
Updates to staff page

### PR DESCRIPTION
**Pull request by jlcohoon**

### CODE REVIEW

**Comment by erinspace** [comment]
Yo @jlcohoon! Looks like there are a few merge conflicts, mind taking a look?

**Comment by jlcohoon** [comment]
better?

**Comment by erinspace** [comment]
Better!

**Comment by GaryKriebel** [comment]
@jlcohoon I noticed that on the live site and even in this pull request:
- Kurtis is listed twice under Alumi
- Kurtis' 2nd listing has some information pertaining to Lauren R
- Josh, Jordan, & Katya are out of order

**Comment by lbanner** [comment]
FYI: This is closed/merged, but on Live Site not seeing:
E Barbour, W Banner, or J Hand.

**Comment by GaryKriebel** [comment]
Server need bouncing, yes?

**Comment by erinspace** [comment]
Just pinged @sloria for update!

**Pull request merged**
