### PR TITLE
update the api call from http to https

### PR DESCRIPTION
**Pull request by GaryKriebel**
Fixes https://github.com/CenterForOpenScience/centerforopenscience.org/issues/508 by making the api call via https instead of http.

### CODE REVIEW

**Comment by sloria** [comment]
This changes [3rd party software](https://github.com/LJXDM/jflickrfeed) which is currently unlicensed. I'm not sure we can make this change until that project adds a license. I've opened an issue: https://github.com/LJXDM/jflickrfeed/issues/1

**Comment by GaryKriebel** [comment]
@sloria, both the 3rd party repo and the author are not very active on GitHub.  Not sure your issue will be looked at in a timely fashion.  Any issue in making the above change so that the photo stream shows again an then update the code if/when a license is added to the repo?

**Comment by sloria** [comment]
The issue is that I don't think we can (legally speaking) make the edit to the file because the author of that plugin retains all rights to modify and distribute the source code.

**Comment by GaryKriebel** [comment]
Should we update the site to remove the photo feed?

**Comment by sloria** [comment]
Either that or use different code to display the feed.

**Comment by atelic** [comment]
Just out of curiosity, why isn't MIT on the file being changed enough? 

https://github.com/GaryKriebel/centerforopenscience.org/blob/patch-1/www/static/plugins/jflickrfeed/jflickrfeed.min.js#L3

**Comment by JeffSpies** [comment]
Nice catch @barbour-em, it is. @sloria, if this fixes our feed, please merge or raise other issues asap. Thanks!

**Comment by GaryKriebel** [comment]
@sloria ... per the thread above, can we roll this out so the photo feed works again?

**Pull request merged**
