### PR TITLE
Update staff page, board, news

### PR DESCRIPTION
**Pull request by jlcohoon**

### CODE REVIEW

**Comment by erinspace** [comment]
Hello @jlcohoon, looks like there are some merge conflicts with this PR - specifically in about_team.mako. If you would't mind resolving those, I can go ahead and merge! If you'd like me to resolve them I'd be happy to (looks pretty minor, but wanted to check with you first before I did anything).

Also it looks like a few folks with new photos didn't get updated somehow - in particular I noticed Harry and Fabian. 

Looks great tho! So many new people!!

**Comment by jlcohoon** [comment]
Should be resolved! New additions seemed to just be causing the conflicts. Good catch with Harry and Fabian!

**Comment by erinspace** [comment]
@jlcohoon hrmmmm merge conflicts still seem to be there somehow... give it another try? Or if you prefer I can just brute foce accept your version as everything looks ok. Lemmie know which you want to try!

**Comment by jlcohoon** [comment]
Accepting my version is all that it needs—it's just the
reordering/additions that are throwing it off. Thank you!

**Comment by erinspace** [comment]
ok cool! I'll take care of it!

**Pull request merged**
